import type { Metadata } from "next";
import { ReactNode } from "react";

type Props = {
  modal: ReactNode; // modal 속성 추가
  children: ReactNode;
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children, modal }: Props) {
  return (
    <>
      {modal}
      {children}
    </>
  );
}
